name: Publish Build

on:
  push:
    branches:
      - master # Altere para a branch principal do seu  projeto

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: build/static/ # or path/to/artifact
